config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root "nodes#index"

  resource :session, only: [ :new, :create, :destroy ]
  resources :nodes do
    member do
      get :health
    end

    resources :container, only: [ :index, :show ] do
      member do
        get :logs
        get "/action/:action_name", to: "container#action", as: :action
      end
    end
    resources :node_deployments
  end
  resources :node_deployments do
    member do
      get :status
    end
  end
end

app/models/node_deployment.rb
class NodeDeployment < ApplicationRecord
  belongs_to :node

  enum :deployment_type, {
    simple_docker_run: 0,
    simple_docker_compose: 1,
    github_action_runner: 2
  }
  enum :deployment_status, {
    pending_init: 0,
    init_failed: 1,
    healthy: 2,
    connection_lost: 3,
    decommissioned: 4
  }

  validates :name, presence: true
  validates :path, presence: true
end

app/controllers/node_deployments_controller.rb
class NodeDeploymentsController < ApplicationController
  def index
    if params[:node_id].present?
      @node = Node.find params[:node_id]
    end

    @node_deployments_grid = NodeDeploymentsGrid.new(params[:node_deployments_grid]) do |scope|
      if @node.present?
        scope.where(node: @node).page(params[:page])
      else
        scope.page(params[:page])
      end
    end
  end

  def show
    @node_deployment = NodeDeployment.find_by params.permit(:id)
  end

  def status
    @node_deployment = NodeDeployment.find_by params.permit(:id)

    n_api = NodeApiService.new(@node_deployment.node)
    if @node_deployment.simple_docker_run?
      res = n_api.container_detail(params[:id], "logs")
    elsif @node_deployment.simple_docker_compose?
      res = n_api.compose_logs(@node_deployment)
    elsif @node_deployment.github_action_runner?
      res = n_api.runner_status(@node_deployment)
    end

    if res && res.code == "200"
      @node_deployment.update deployment_status: :healthy

      if @node_deployment.github_action_runner?
        @status = res.body
      else
        @status = JSON.parse(res.body)
      end
    else
      @node_deployment.update deployment_status: :connection_lost

      @status = ""
    end
  end

  def new
    @node_deployment = NodeDeployment.new

    if params[:node_id].present?
      @node = Node.find params[:node_id]
      @node_deployment.node = @node
    end
  end

  def create
    @node_deployment = NodeDeployment.new permit(params)

    respond_to do |format|
      if @node_deployment.save
        # Start setup deployment
        Thread.new do
          setup_deployment(@node_deployment, params.require(:node_deployment).permit(:github_token, :adopt))
        end

        flash[:success] = t("messages.model.created")
        format.html { redirect_to action: "show", id: @node_deployment.id }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @node_deployment = NodeDeployment.find_by params.permit(:id)
  end

  def update
    @node_deployment = NodeDeployment.find_by params.permit(:id)

    respond_to do |format|
      if @node_deployment.update permit(params)
        # Update deployment data
        Thread.new do
          update_deployment(@node_deployment)
        end
        format.html { redirect_to action: "show", id: @node_deployment.id }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    NodeDeployment.find_by(params.permit(:id)).destroy
    flash[:danger] = t("messages.model.deleted")
    redirect_to action: "index"
  end

  private

  def permit(params)
    params.require(:node_deployment).permit(
      :node_id,
      :name,
      :path,
      :git_url,
      :deployment_type,
      :compose,
    )
  end

  def setup_deployment(node_deployment, permitted_params)
    node_api = NodeApiService.new(node_deployment.node)
    # Test if node healthy
    response = node_api.health()
    if response && response.code == "200"

      unless permitted_params[:adopt] == "1"
        if node_deployment.simple_docker_run?
          response = node_api.container_create(node_deployment)
        elsif node_deployment.simple_docker_compose?
          response = node_api.setup_compose(node_deployment)
        elsif node_deployment.github_action_runner?
          response = node_api.setup_runner(node_deployment, permitted_params[:github_token])
        end
        if response && response.code == "200"
          logger.info(response.body)
          node_deployment.update deployment_status: :healthy
        else
          logger.warn("Deployment failed!")
          logger.warn(response.body)
          node_deployment.update deployment_status: :init_failed
        end
      else
        node_deployment.update deployment_status: :healthy
      end

    else
      logger.warn("Deployment failed! Node not healthy")
      node_deployment.update deployment_status: :init_failed
    end
  end

  def update_deployment(node_deployment)
    node_api = NodeApiService.new(node_deployment.node)
    # Test if node healthy
    response = node_api.health()
    if response && response.code == "200"

      if node_deployment.simple_docker_run?
        response = node_api.container_create(node_deployment)
      elsif node_deployment.simple_docker_compose?
        response = node_api.setup_compose(node_deployment)
      elsif node_deployment.github_action_runner?
        return
      end
      if response && response.code == "200"
        logger.info(response.body)
        node_deployment.update deployment_status: :healthy
      else
        logger.warn("Deployment update failed!")
        logger.warn(response.body)
        node_deployment.update deployment_status: :init_failed
      end

    else
      logger.warn("Deployment update failed! Node not healthy")
      node_deployment.update deployment_status: :init_failed
    end
  end
end

app/views/node_deployments/_form.html.haml
.card.mt-3
  %h5.card-header.d-flex.justify-content-between.align-items-center
    = NodeDeployment.model_name.human
    .d-flex.model-buttons
      - if @node_deployment.id.present?
        = button_to t('helpers.submit.delete'), node_deployment_path(@node_deployment), class: 'btn btn-danger', method: :delete
      = button_to t('helpers.submit.cancel'), node_deployments_path, class: 'btn btn-secondary', method: :get

  .card-body
    = simple_form_for @node_deployment do |f|
      = f.association :node
      = f.input :name
      = f.input :path
      = f.input :git_url, as: :url
      = f.input :deployment_type, collection: NodeDeployment.deployment_types.symbolize_keys.keys, include_blank: false, include_hidden: false
      = f.input :compose, as: :text
      - unless @node_deployment.id.present?
        = f.input :github_token, input_html: { value: "" }
        = f.input :adopt, as: :boolean, input_html: { checked: false }
        
      = f.submit class: 'btn btn-primary mt-2'

app/views/node_deployments/edit.html.haml
= render partial: 'form'

app/views/node_deployments/index.html.haml
%turbo-frame#node_deployments
  .card.mt-3
    %h5.card-header.d-flex.justify-content-between.align-items-center
      = NodeDeployment.model_name.human
      .d-flex.model-buttons
        - if @node.present?
          = button_to t('helpers.submit.create', model: NodeDeployment.model_name.human), new_node_node_deployment_path(@node), class: 'btn btn-primary', method: :get, form: { "data-turbo-frame": "_top" }
        - else
          = button_to t('helpers.submit.create', model: NodeDeployment.model_name.human), new_node_deployment_path, class: 'btn btn-primary', method: :get, form: { "data-turbo-frame": "_top" }
    .table-responsive
      = datagrid_form_with model: @node_deployments_grid, url: nodes_path
      = datagrid_table @node_deployments_grid
      = paginate @node_deployments_grid.assets

app/views/node_deployments/new.html.haml
= render partial: 'form'

app/views/node_deployments/show.html.haml
- if @node_deployment.pending_init?
  .card.mt-3
    .card-body.d-flex.justify-content-center.flex-column.align-items-center
      .spinner-border{role: "status"}
        %span.visually-hidden Loading...
      %span
        = t('views.node_deployment.pending_init')

- elsif @node_deployment.init_failed?
  .card.mt-3
    .card-body.d-flex.justify-content-center.flex-column.align-items-center
      = icon 'exclamation-diamond'
      %span
        = t('views.node_deployment.init_failed')
- elsif @node_deployment.connection_lost?
  .card.mt-3.text-danger
    .card-body.d-flex.justify-content-center.flex-column.align-items-center
      = icon 'exclamation-diamond'
      %span
        = t('views.node_deployment.connection_lost')
- elsif @node_deployment.healthy?
  = turbo_frame_tag 'deployment_status', src: status_node_deployment_path(@node_deployment) do
    .card.mt-3
      .card-body.d-flex.justify-content-center
        .spinner-border{role: "status"}
          %span.visually-hidden Loading...

app/views/node_deployments/status.html.haml
%turbo-frame#deployment_status
  .card.mt-3
    %h5.card-header.d-flex.justify-content-between.align-items-center
      = t('activerecord.models.node_deployment')
      .d-flex.model-buttons
        = button_to t('helpers.navigate.back'), node_path(@node_deployment.node), class: 'btn btn-primary', method: :get, form: { "data-turbo-frame": "_top" }
    .card-body
      %pre.mt-2.vh-80
        %code{data: {controller: 'ansi-color'}}
          - if @status.kind_of?(Array)
            - @status.each do |line|
              = line
          - else
            = @status