config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root "nodes#index"

  resource :session, only: [ :new, :create, :destroy ]
  resources :nodes do
    member do
      get :health
    end

    resources :container, only: [ :index, :show ] do
      member do
        get :logs
        get "/action/:action_name", to: "container#action", as: :action
      end
    end
    resources :node_deployments
  end
  resources :node_deployments do
    member do
      get :status
    end
  end
end

app/models/node.rb
class Node < ApplicationRecord
  enum :node_status, {
    pending_init: 0,
    init_failed: 1,
    healthy: 2,
    connection_lost: 3,
    decommissioned: 4
  }
  encrypts :key

  has_many :node_deployments

  validates :hostname, presence: true
  validates :ip, presence: true, format: {
    with: /\A(
      (25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])\.  # IPv4 octet 1
      (25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])\.  # IPv4 octet 2
      (25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])\.  # IPv4 octet 3
      (25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])    # IPv4 octet 4
    |
      (
        ([0-9A-Fa-f]{1,4}:){7}[0-9A-Fa-f]{1,4}|
        ([0-9A-Fa-f]{1,4}:){1,7}:|
        :(:[0-9A-Fa-f]{1,4}){1,7}|
        ([0-9A-Fa-f]{1,4}:){1,6}:[0-9A-Fa-f]{1,4}|
        ([0-9A-Fa-f]{1,4}:){1,5}(:[0-9A-Fa-f]{1,4}){1,2}|
        ([0-9A-Fa-f]{1,4}:){1,4}(:[0-9A-Fa-f]{1,4}){1,3}|
        ([0-9A-Fa-f]{1,4}:){1,3}(:[0-9A-Fa-f]{1,4}){1,4}|
        ([0-9A-Fa-f]{1,4}:){1,2}(:[0-9A-Fa-f]{1,4}){1,5}|
        [0-9A-Fa-f]{1,4}:(:[0-9A-Fa-f]{1,4}){1,6}|
        :(:[0-9A-Fa-f]{1,4}){1,6}
      )
    )\z/x
  }
  validates :api_url, presence: true
  validates :port, presence: true
  validates :key, presence: true, length: { minimum: 16 }

  def to_s
    "#{self.hostname} (#{self.ip})"
  end
end

app/controllers/nodes_controller.rb
class NodesController < ApplicationController
  def index
    @nodes_grid = NodesGrid.new(params[:nodes_grid]) do |scope|
      scope.page(params[:page])
    end
  end

  def show
    @node = Node.find_by params.permit(:id)

    unless @node.healthy? || @node.pending_init?
      Thread.new do
        n_api = NodeApiService.new(@node)
        res = n_api.health()
        if res && res.code == "200"
          @node.update node_status: :healthy
          @health_data = JSON.parse(res.body)
        end
      end
    end
  end

  def health
    @node = Node.find_by params.permit(:id)

    n_api = NodeApiService.new(@node)
    res = n_api.health()
    if res && res.code == "200"
      @node.update node_status: :healthy
      @health_data = JSON.parse(res.body)
    else
      @node.update node_status: :connection_lost
      @health_data = JSON.parse('{
        "memory_total": -1,
        "memory_available": -1,
        "memory_swapped": -1,
        "memory_free": -1,
        "memory_buffer": -1,
        "memory_cache": -1,
        "io_bytes_in": -1,
        "io_bytes_out": -1,
        "cpu_usage": -1
      }')
    end
  end

  def new
    @node = Node.new
  end

  def create
    @node = Node.new permit(params)

    respond_to do |format|
      if @node.save
        # Start adopt node process
        Thread.new do
          node_api = NodeApiService.new(@node)
          20.times do |n|
            response = node_api.health()
            if response.code == "200"
              @node.update node_status: :healthy
              break
            end
            sleep 10
          end

          @node.update node_status: :init_failed unless @node.healthy?
        end

        flash[:success] = t("messages.model.created")
        format.html { redirect_to action: "show", id: @node.id }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @node = Node.find_by params.permit(:id)
  end

  def update
    @node = Node.find_by params.permit(:id)

    respond_to do |format|
      if @node.update permit(params)
        format.html { redirect_to action: "show", id: @node.id }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    Node.find_by(params.permit(:id)).destroy
    flash[:danger] = t("messages.model.deleted")
    redirect_to action: "index"
  end

  private

  def permit(params)
    params.require(:node).permit(
      :hostname,
      :ip,
      :api_url,
      :port,
      :key,
    )
  end
end

app/views/nodes/_form.html.haml
.card.mt-3
  %h5.card-header.d-flex.justify-content-between.align-items-center
    = Node.model_name.human
    .d-flex.model-buttons
      - if @node.id.present?
        = button_to t('helpers.submit.delete'), node_path(@node), class: 'btn btn-danger', method: :delete
      = button_to t('helpers.submit.cancel'), nodes_path, class: 'btn btn-secondary', method: :get

  .card-body
    = simple_form_for @node do |f|
      = f.input :hostname
      = f.input :ip
      = f.input :api_url
      = f.input :port
      = f.input :key, as: :password
        
      = f.submit class: 'btn btn-primary mt-2'

app/views/nodes/edit.html.haml
.card.mt-3
  .card-body
    = t 'views.nodes.update_hint'
    %pre.mt-2
      %code{data: {controller: 'replace-url'}}
        = "curl -fsSL $$BASE_URL$$/update.sh | sudo bash -s -- \"$$BASE_URL$$\""

= render partial: 'form'

app/views/nodes/health.html.haml
%turbo-frame#node_health
  .card.mt-3
    .card-body
      .h5.card-title
        = @node
      .row
        .col
          .d-flex.justify-content-center.flex-column.align-items-center
            .meter{data: {controller: 'meter', value: @health_data["cpu_usage"]}}
            .h5
              CPU
        .col
          .d-flex.justify-content-center.flex-column.align-items-center
            .meter{data: {controller: 'meter', value: ((1-(@health_data["memory_available"].to_f / @health_data["memory_total"])) * 100).to_i}}
            .h5
              Memory
        .col-6
          .row
            .col-md-3.mt-3
              .h5
                = @health_data["memory_free"]
              Memory free
            .col-md-3.mt-3
              .h5
                = @health_data["memory_swapped"]
              Memory swap
            .col-md-3.mt-3
              .h5
                = @health_data["memory_buffer"]
              Memory buffered
            .col-md-3.mt-3
              .h5
                = @health_data["memory_cache"]
              Memory cache
            .col-md-3.mt-3
              .h5
                = @health_data["io_bytes_in"]
              IO in
            .col-md-3.mt-3
              .h5
                = @health_data["io_bytes_out"]
              IO out
        .col-1.d-flex.justify-content-end
          = button_to t('helpers.refresh'), health_node_path(@node), class: 'btn btn-primary', method: :get

app/views/nodes/index.html.haml
.card.mt-3
  %h5.card-header.d-flex.justify-content-between.align-items-center
    = Node.model_name.human
    .d-flex.model-buttons
      = button_to t('helpers.submit.create', model: Node.model_name.human), new_node_path, class: 'btn btn-primary', method: :get
  .table-responsive
    = datagrid_form_with model: @nodes_grid, url: nodes_path
    = datagrid_table @nodes_grid
    = paginate @nodes_grid.assets

app/views/nodes/new.html.haml
.card.mt-3
  .card-body
    = t 'views.nodes.install_hint'
    %pre.mt-2
      %code{data: {controller: 'replace-url'}}
        = "curl -fsSL $$BASE_URL$$/install.sh | sudo bash -s -- \"$$BASE_URL$$\" BASE_DOMAIN_OF_SERVER \"#{current_user.email}\""

= render partial: 'form'

app/views/nodes/show.html.haml
- if @node.pending_init?
  .card.mt-3
    .card-body.d-flex.justify-content-center.flex-column.align-items-center
      .spinner-border{role: "status"}
        %span.visually-hidden Loading...
      %span
        = t('views.nodes.pending_init')

- elsif @node.init_failed?
  .card.mt-3
    .card-body.d-flex.justify-content-center.flex-column.align-items-center
      = icon 'exclamation-diamond'
      %span
        = t('views.nodes.init_failed')
- elsif @node.connection_lost?
  .card.mt-3.text-danger
    .card-body.d-flex.justify-content-center.flex-column.align-items-center
      = icon 'exclamation-diamond'
      %span
        = t('views.nodes.connection_lost')
- else
  = turbo_frame_tag 'node_health', src: health_node_path(@node) do
    .card.mt-3
      .card-body.d-flex.justify-content-center
        .spinner-border{role: "status"}
          %span.visually-hidden Loading...
  = turbo_frame_tag 'containers', src: node_container_index_path(@node) do
    .card.mt-3
      .card-body.d-flex.justify-content-center
        .spinner-border{role: "status"}
          %span.visually-hidden Loading...
  = turbo_frame_tag 'node_deployments', src: node_node_deployments_path(@node) do
    .card.mt-3
      .card-body.d-flex.justify-content-center
        .spinner-border{role: "status"}
          %span.visually-hidden Loading...