config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root "nodes#index"

  resource :session, only: [ :new, :create, :destroy ]
  resources :nodes do
    member do
      get :health
    end

    resources :container, only: [ :index, :show ] do
      member do
        get :logs
        get "/action/:action_name", to: "container#action", as: :action
      end
    end
    resources :node_deployments
  end
  resources :node_deployments do
    member do
      get :status
    end
  end
end

app/controllers/container_controller.rb
class ContainerController < ApplicationController
  def index
    @node = Node.find params[:node_id]

    n_api = NodeApiService.new(@node)
    res = n_api.container()
    if res && res.code == "200"
      @node.update node_status: :healthy
      @containers = JSON.parse(res.body)
      @containers.each { |c| c[:node_id] = @node.id }

      @container_grid = ContainerGrid.new(params[:container_grid]) do |scope|
        scope = @containers
      end
    else
      @node.update node_status: :connection_lost
    end
  end

  def show
    @node = Node.find params[:node_id]

    n_api = NodeApiService.new(@node)
    res = n_api.container_detail(params[:id], "inspect")
    if res && res.code == "200"
      @node.update node_status: :healthy
      @container_detail = JSON.pretty_generate(JSON.parse(res.body))
    else
      @node.update node_status: :connection_lost
      @container_detail = ""
    end
  end

  def logs
    @node = Node.find params[:node_id]

    n_api = NodeApiService.new(@node)
    res = n_api.container_detail(params[:id], "logs")
    if res && res.code == "200"
      @node.update node_status: :healthy
      @container_logs = JSON.parse(res.body)
    else
      @node.update node_status: :connection_lost
      @container_logs = []
    end
  end

  def action
    @node = Node.find params[:node_id]

    n_api = NodeApiService.new(@node)
    res = n_api.container_detail(params[:id], params[:action_name])

    respond_to do |format|
      if res && res.code == "200"
        if params[:action_name] == "rm"
          format.html { redirect_to node_path(@node) }
        else
          format.html { redirect_to node_container_path(@node, params[:id]) }
        end
      else
        flash[:danger] = t("messages.container.action.fail")
        format.html { redirect_to node_container_path(@node, params[:id]) }
      end
    end
  end
end

app/views/container/index.html.haml
%turbo-frame#containers
  .card.mt-3
    %h5.card-header.d-flex.justify-content-between.align-items-center
      = t('activerecord.models.container')
      .d-flex.model-buttons
        = button_to t('helpers.refresh'), node_container_index_path(@node), class: 'btn btn-primary', method: :get
    .table-responsive
      - if @container_grid.present?
        = datagrid_table @container_grid

app/views/container/logs.html.haml
.card.mt-3
  %h5.card-header.d-flex.justify-content-between.align-items-center
    = "#{t('activerecord.models.container')} (#{params[:id]})"
    .d-flex.model-buttons
      = button_to t('helpers.navigate.back'), node_path(@node), class: 'btn btn-primary', method: :get
  .card-body
    %pre.mt-2.vh-80
      %code{data: {controller: 'ansi-color'}}
        - @container_logs.each do |line|
          = line

app/views/container/show.html.haml
.card.mt-3
  %h5.card-header.d-flex.justify-content-between.align-items-center
    = "#{t('activerecord.models.container')} (#{params[:id]})"
    .d-flex.model-buttons
      = button_to(action_node_container_path(@node, params[:id], "start"), class: "btn btn-primary", method: :get, form: { data: { turbo_frame: "_top"} }) do
        = icon "play-fill"
      = button_to(action_node_container_path(@node, params[:id], "stop"), class: "btn btn-danger", method: :get, form: { data: { turbo_confirm: t("helpers.submit.confirm"), turbo_frame: "_top"} }) do
        = icon "stop-fill"
      = button_to(action_node_container_path(@node, params[:id], "rm"), class: "btn btn-danger", method: :get, form: { data: { turbo_confirm: t("helpers.submit.confirm"), turbo_frame: "_top"} }) do
        = icon "trash"
      = button_to t("helpers.navigate.back"), node_path(@node), class: "btn btn-primary", method: :get
  .card-body
    %pre.mt-2.vh-80
      %code
        = @container_detail