config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root "nodes#index"

  resource :session, only: [ :new, :create, :destroy ]
  resources :nodes do
    member do
      get :health
    end

    resources :container, only: [ :index, :show ] do
      member do
        get :logs
        get "/action/:action_name", to: "container#action", as: :action
      end
    end
    resources :node_deployments
  end
  resources :node_deployments do
    member do
      get :status
    end
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title= content_for(:title) || "Deployment Manager"
    %meta{content: "width=device-width,initial-scale=1", name: "viewport"}/
    %meta{content: "yes", name: "apple-mobile-web-app-capable"}/
    %meta{content: "Deployment Manager", name: "application-name"}/
    %meta{content: "yes", name: "mobile-web-app-capable"}/
    = csrf_meta_tags
    = csp_meta_tag
    = yield :head
    %link{href: "/icon.png", rel: "icon", type: "image/png"}/
    %link{href: "/icon.svg", rel: "icon", type: "image/svg+xml"}/
    %link{href: "/icon.png", rel: "apple-touch-icon"}/
    %link{href: "https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css ", rel: "stylesheet"}/
    = stylesheet_link_tag 'application', 'data-turbo-track': 'reload'
    = javascript_importmap_tags
    - translation_json = current_translations.to_json.gsub("\\n", "").html_safe
    %script#i18n{:type => "application/json"}
      = raw translation_json
      
  %body.bg-dark
    %nav.navbar.navbar-expand-lg.navbar-light.bg-light
      .container-fluid
        %a.navbar-brand
          Deployment Manager
        %button.navbar-toggler{ data: {bs: {toggle: 'collapse', target: '#navbarToggler'}}, aria: {controls: 'navbarToggler', expanded: false, label: 'Toggle navigation'}, type: 'button'}
          %span.navbar-toggler-icon
        .collapse.navbar-collapse{ id: 'navbarToggler' }
          %ul.navbar-nav.me-auto.mb-2.mb-lg-0
            = nav_item 'Home', root_path
            = nav_item 'Nodes', nodes_path
            = nav_item 'Deployments', node_deployments_path
          - if current_user
            = button_to t('login.logout'), session_path, class: 'btn btn-danger', method: :delete

    .container-fluid{id: :flashbox }
      - flash.each do |key, value|
        .alert.alert-dismissible.mt-3{class: "alert-#{key}", role: 'alert'}
          = value
          %button.btn-close.close{data: {bs: {dismiss: 'alert'}}, aria: {label: 'Close'}, type: 'button'}
    .container-fluid.pb-4
      = yield